spring:
  application.name: spring-boot-classloader-sample
  config.name: application

  main:
    web-environment: true
    show-banner: true
    log-startup-info: true

security:
    basic.enabled: true
    
management:
    contextPath: /mgmt

server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE